# Generated by Django 5.2.5 on 2025-10-12 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("GRADE_CREATE", "Note créée"),
                            ("GRADE_UPDATE", "Note modifiée"),
                            ("GRADE_DELETE", "Note supprimée"),
                            ("INVOICE_CREATE", "Facture créée"),
                            ("INVOICE_UPDATE", "Facture modifiée"),
                            ("INVOICE_DELETE", "Facture supprimée"),
                            ("INVOICE_SEND", "Facture envoyée"),
                            ("INVOICE_CANCEL", "Facture annulée"),
                            ("PAYMENT_CREATE", "Paiement créé"),
                            ("PAYMENT_UPDATE", "Paiement modifié"),
                            ("PAYMENT_DELETE", "Paiement supprimé"),
                            ("PAYMENT_APPROVE", "Paiement approuvé"),
                            ("PAYMENT_REJECT", "Paiement rejeté"),
                            ("ATTENDANCE_CREATE", "Présence enregistrée"),
                            ("ATTENDANCE_UPDATE", "Présence modifiée"),
                            ("ATTENDANCE_DELETE", "Présence supprimée"),
                            ("DOCUMENT_CREATE", "Document ajouté"),
                            ("DOCUMENT_UPDATE", "Document modifié"),
                            ("DOCUMENT_DELETE", "Document supprimé"),
                            ("SESSION_CREATE", "Session créée"),
                            ("SESSION_UPDATE", "Session modifiée"),
                            ("SESSION_DELETE", "Session supprimée"),
                            ("USER_CREATE", "Utilisateur créé"),
                            ("USER_UPDATE", "Utilisateur modifié"),
                            ("USER_DELETE", "Utilisateur supprimé"),
                            ("USER_LOGIN", "Connexion"),
                            ("USER_LOGOUT", "Déconnexion"),
                            ("OTHER", "Autre action"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date et heure",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description détaillée de l'action",
                        verbose_name="Description",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Grade, Invoice, Payment",
                        max_length=50,
                        verbose_name="Type d'objet",
                    ),
                ),
                (
                    "object_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de l'objet"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Représentation de l'objet",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="État avant modification (JSON)",
                        null=True,
                        verbose_name="Anciennes valeurs",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="État après modification (JSON)",
                        null=True,
                        verbose_name="Nouvelles valeurs",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="Navigateur utilisé",
                        max_length=255,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'activité",
                "verbose_name_plural": "Journal des activités",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "user"],
                        name="core_activi_timesta_05b791_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-timestamp"],
                        name="core_activi_action__821553_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_activi_content_fdc4af_idx",
                    ),
                ],
            },
        ),
    ]
