# Generated by Django 5.2.5 on 2025-10-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
