# Generated by Django 5.2.5 on 2025-10-13 18:35

import django.core.validators
import django.db.models.deletion
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nom du type de frais"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Frais récurrent"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=True, verbose_name="Frais obligatoire"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Type de frais",
                "verbose_name_plural": "Types de frais",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "requires_reference",
                    models.BooleanField(
                        default=False, verbose_name="Nécessite une référence"
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, verbose_name="URL de webhook"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Méthode de paiement",
                "verbose_name_plural": "Méthodes de paiement",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALARIES", "Salaires"),
                            ("UTILITIES", "Services publics"),
                            ("SUPPLIES", "Fournitures"),
                            ("MAINTENANCE", "Maintenance"),
                            ("EQUIPMENT", "Équipement"),
                            ("TRANSPORTATION", "Transport"),
                            ("FOOD", "Alimentation"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "expense_date",
                    models.DateField(
                        default=finance.models.get_current_date,
                        verbose_name="Date de dépense",
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/",
                        verbose_name="Reçu/Facture",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Approuvé"),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'approbation"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_expenses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépense",
                "verbose_name_plural": "Dépenses",
                "ordering": ["-expense_date"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Numéro de facture"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        default=finance.models.get_current_date,
                        verbose_name="Date d'émission",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Date d'échéance")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Remise",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Montant total",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SENT", "Envoyée"),
                            ("PAID", "Payée"),
                            ("OVERDUE", "En retard"),
                            ("CANCELLED", "Annulée"),
                        ],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="accounts.parent",
                        verbose_name="Parent responsable",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="accounts.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=5,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.feetype",
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.invoice",
                        verbose_name="Facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de facture",
                "verbose_name_plural": "Lignes de facture",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID de transaction"
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=finance.models.get_current_datetime,
                        verbose_name="Date de paiement",
                    ),
                ),
                (
                    "processed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("COMPLETED", "Terminé"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Réponse de la passerelle"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="finance.invoice",
                        verbose_name="Facture",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.paymentmethod",
                        verbose_name="Méthode de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la bourse"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Pourcentage"),
                            ("FIXED_AMOUNT", "Montant fixe"),
                            ("FULL", "Gratuit total"),
                        ],
                        max_length=15,
                        verbose_name="Type de bourse",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Pourcentage",
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant fixe",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academic.academicyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "eligible_levels",
                    models.ManyToManyField(
                        to="academic.level", verbose_name="Niveaux éligibles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bourse",
                "verbose_name_plural": "Bourses",
            },
        ),
        migrations.CreateModel(
            name="DailyFinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        db_index=True, unique=True, verbose_name="Date du rapport"
                    ),
                ),
                (
                    "payments_count",
                    models.IntegerField(default=0, verbose_name="Nombre de paiements"),
                ),
                (
                    "payments_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total encaissé",
                    ),
                ),
                (
                    "payments_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Espèces",
                    ),
                ),
                (
                    "payments_check",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Chèques",
                    ),
                ),
                (
                    "payments_transfer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Virements",
                    ),
                ),
                (
                    "payments_card",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Cartes bancaires",
                    ),
                ),
                (
                    "payments_mobile",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Paiements mobiles",
                    ),
                ),
                (
                    "invoices_created_count",
                    models.IntegerField(default=0, verbose_name="Factures créées"),
                ),
                (
                    "invoices_created_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant facturé",
                    ),
                ),
                (
                    "invoices_pending_count",
                    models.IntegerField(default=0, verbose_name="Factures en attente"),
                ),
                (
                    "invoices_pending_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant en attente",
                    ),
                ),
                (
                    "invoices_paid_count",
                    models.IntegerField(default=0, verbose_name="Factures payées"),
                ),
                (
                    "invoices_paid_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "invoices_overdue_count",
                    models.IntegerField(default=0, verbose_name="Factures en retard"),
                ),
                (
                    "invoices_overdue_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant en retard",
                    ),
                ),
                (
                    "invoices_partial_count",
                    models.IntegerField(default=0, verbose_name="Factures partielles"),
                ),
                (
                    "invoices_partial_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Solde partiel",
                    ),
                ),
                (
                    "payments_diff_previous_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Différence de paiements vs jour précédent",
                        max_digits=15,
                        verbose_name="Différence jour précédent",
                    ),
                ),
                (
                    "payments_diff_previous_day_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="% jour précédent",
                    ),
                ),
                (
                    "payments_diff_previous_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Différence semaine précédente",
                    ),
                ),
                (
                    "payments_diff_previous_week_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="% semaine précédente",
                    ),
                ),
                (
                    "monthly_average_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Moyenne mensuelle",
                    ),
                ),
                (
                    "total_receivables",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant total à recevoir",
                        max_digits=15,
                        verbose_name="Créances totales",
                    ),
                ),
                (
                    "collection_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pourcentage de paiements reçus vs facturé",
                        max_digits=5,
                        verbose_name="Taux de recouvrement (%)",
                    ),
                ),
                (
                    "expenses_count",
                    models.IntegerField(default=0, verbose_name="Nombre de dépenses"),
                ),
                (
                    "expenses_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total dépenses",
                    ),
                ),
                (
                    "net_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Encaissements - Dépenses",
                        max_digits=15,
                        verbose_name="Balance nette",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Généré le"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email envoyé"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email envoyé le"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes et observations"),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stockage de données complexes pour graphiques et analyses",
                        verbose_name="Données supplémentaires",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Généré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport financier journalier",
                "verbose_name_plural": "Rapports financiers journaliers",
                "ordering": ["-report_date"],
                "indexes": [
                    models.Index(
                        fields=["-report_date"], name="finance_dai_report__aee437_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="finance_dai_generat_9a2124_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="academic.academicyear",
                        verbose_name="Année scolaire",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_structures",
                        to="academic.level",
                        verbose_name="Niveau",
                    ),
                ),
                (
                    "fee_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="finance.feetype",
                        verbose_name="Type de frais",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure de frais",
                "verbose_name_plural": "Structures de frais",
                "unique_together": {("fee_type", "level", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Début de période")),
                ("period_end", models.DateField(verbose_name="Fin de période")),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salaire de base"
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Indemnités",
                    ),
                ),
                (
                    "overtime_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Heures supplémentaires",
                    ),
                ),
                (
                    "tax_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Impôts",
                    ),
                ),
                (
                    "social_security",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Sécurité sociale",
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Autres déductions",
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salaire brut"
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salaire net"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("CALCULATED", "Calculée"),
                            ("APPROVED", "Approuvée"),
                            ("PAID", "Payée"),
                        ],
                        default="DRAFT",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payrolls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculated_payrolls",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Calculé par",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to="accounts.teacher",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paie",
                "verbose_name_plural": "Paies",
                "ordering": ["-period_start"],
                "unique_together": {("employee", "period_start", "period_end")},
            },
        ),
        migrations.CreateModel(
            name="ScholarshipApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_date",
                    models.DateField(
                        default=finance.models.get_current_date,
                        verbose_name="Date de demande",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                            ("SUSPENDED", "Suspendue"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("justification", models.TextField(verbose_name="Justification")),
                (
                    "supporting_documents",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="scholarships/",
                        verbose_name="Documents justificatifs",
                    ),
                ),
                (
                    "decision_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de décision"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, verbose_name="Notes de décision"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_scholarships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approuvé par",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="finance.scholarship",
                        verbose_name="Bourse",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarship_applications",
                        to="accounts.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de bourse",
                "verbose_name_plural": "Demandes de bourse",
                "unique_together": {("scholarship", "student")},
            },
        ),
    ]
