# Generated by Django 5.2.5 on 2025-09-06 14:56

import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(
                default=finance.models.get_current_date, verbose_name="Date de dépense"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=finance.models.get_current_date, verbose_name="Date d'émission"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                default=finance.models.get_current_datetime,
                verbose_name="Date de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="scholarshipapplication",
            name="application_date",
            field=models.DateField(
                default=finance.models.get_current_date, verbose_name="Date de demande"
            ),
        ),
    ]
