# Generated by Django 5.2.5 on 2025-10-12 12:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_fix_timezone_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyFinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        db_index=True, unique=True, verbose_name="Date du rapport"
                    ),
                ),
                (
                    "payments_count",
                    models.IntegerField(default=0, verbose_name="Nombre de paiements"),
                ),
                (
                    "payments_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total encaissé",
                    ),
                ),
                (
                    "payments_cash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Espèces",
                    ),
                ),
                (
                    "payments_check",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Chèques",
                    ),
                ),
                (
                    "payments_transfer",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Virements",
                    ),
                ),
                (
                    "payments_card",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Cartes bancaires",
                    ),
                ),
                (
                    "payments_mobile",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Paiements mobiles",
                    ),
                ),
                (
                    "invoices_created_count",
                    models.IntegerField(default=0, verbose_name="Factures créées"),
                ),
                (
                    "invoices_created_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant facturé",
                    ),
                ),
                (
                    "invoices_pending_count",
                    models.IntegerField(default=0, verbose_name="Factures en attente"),
                ),
                (
                    "invoices_pending_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant en attente",
                    ),
                ),
                (
                    "invoices_paid_count",
                    models.IntegerField(default=0, verbose_name="Factures payées"),
                ),
                (
                    "invoices_paid_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "invoices_overdue_count",
                    models.IntegerField(default=0, verbose_name="Factures en retard"),
                ),
                (
                    "invoices_overdue_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Montant en retard",
                    ),
                ),
                (
                    "invoices_partial_count",
                    models.IntegerField(default=0, verbose_name="Factures partielles"),
                ),
                (
                    "invoices_partial_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Solde partiel",
                    ),
                ),
                (
                    "payments_diff_previous_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Différence de paiements vs jour précédent",
                        max_digits=15,
                        verbose_name="Différence jour précédent",
                    ),
                ),
                (
                    "payments_diff_previous_day_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="% jour précédent",
                    ),
                ),
                (
                    "payments_diff_previous_week",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Différence semaine précédente",
                    ),
                ),
                (
                    "payments_diff_previous_week_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="% semaine précédente",
                    ),
                ),
                (
                    "monthly_average_payments",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Moyenne mensuelle",
                    ),
                ),
                (
                    "total_receivables",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant total à recevoir",
                        max_digits=15,
                        verbose_name="Créances totales",
                    ),
                ),
                (
                    "collection_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pourcentage de paiements reçus vs facturé",
                        max_digits=5,
                        verbose_name="Taux de recouvrement (%)",
                    ),
                ),
                (
                    "expenses_count",
                    models.IntegerField(default=0, verbose_name="Nombre de dépenses"),
                ),
                (
                    "expenses_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Total dépenses",
                    ),
                ),
                (
                    "net_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Encaissements - Dépenses",
                        max_digits=15,
                        verbose_name="Balance nette",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Généré le"),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="Email envoyé"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Email envoyé le"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes et observations"),
                ),
                (
                    "additional_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stockage de données complexes pour graphiques et analyses",
                        verbose_name="Données supplémentaires",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Généré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport financier journalier",
                "verbose_name_plural": "Rapports financiers journaliers",
                "ordering": ["-report_date"],
                "indexes": [
                    models.Index(
                        fields=["-report_date"], name="finance_dai_report__aee437_idx"
                    ),
                    models.Index(
                        fields=["generated_at"], name="finance_dai_generat_9a2124_idx"
                    ),
                ],
            },
        ),
    ]
