# Generated by Django 5.2.5 on 2025-09-06 14:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                default=accounts.models.get_current_date,
                verbose_name="Date d'inscription",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="hire_date",
            field=models.DateField(
                default=accounts.models.get_current_date, verbose_name="Date d'embauche"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=accounts.models.get_current_datetime,
                verbose_name="Date d'inscription",
            ),
        ),
    ]
