# Generated by Django 5.2.5 on 2025-10-13 18:35

import academic.models
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Nom de l'année scolaire"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Année courante"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Année scolaire",
                "verbose_name_plural": "Années scolaires",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("ABSENT", "Absent"),
                            ("LATE", "En retard"),
                            ("EXCUSED", "Absent excusé"),
                        ],
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Présence (Ancien)",
                "verbose_name_plural": "Présences (Ancien)",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom de la classe"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=30, verbose_name="Capacité"),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de salle"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
                "ordering": ["level__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyAttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de sessions"
                    ),
                ),
                (
                    "present_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions présentes"
                    ),
                ),
                (
                    "absent_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions absentes"
                    ),
                ),
                (
                    "late_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions en retard"
                    ),
                ),
                (
                    "excused_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions excusées"
                    ),
                ),
                (
                    "daily_status",
                    models.CharField(
                        choices=[
                            ("FULLY_PRESENT", "Entièrement présent"),
                            ("PARTIALLY_PRESENT", "Partiellement présent"),
                            ("MOSTLY_ABSENT", "Majoritairement absent"),
                            ("FULLY_ABSENT", "Entièrement absent"),
                        ],
                        max_length=20,
                        verbose_name="Statut journalier",
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux de présence (%)",
                    ),
                ),
                (
                    "first_arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Première arrivée"
                    ),
                ),
                (
                    "total_late_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total minutes de retard"
                    ),
                ),
                (
                    "justification_provided",
                    models.BooleanField(
                        default=False, verbose_name="Justification fournie"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Résumé quotidien de présence",
                "verbose_name_plural": "Résumés quotidiens de présence",
                "ordering": ["-date", "student__user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du document"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("COURSE", "Cours"),
                            ("EXERCISE", "Exercices"),
                            ("EXAM", "Examen"),
                            ("CORRECTION", "Correction"),
                            ("REFERENCE", "Référence"),
                            ("OTHER", "Autre"),
                        ],
                        default="COURSE",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/", verbose_name="Fichier"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier (bytes)"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type de fichier"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Visible par les étudiants"
                    ),
                ),
                (
                    "is_downloadable",
                    models.BooleanField(default=True, verbose_name="Téléchargeable"),
                ),
                (
                    "access_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de mise à disposition"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("VIEW", "Vue"), ("DOWNLOAD", "Téléchargement")],
                        max_length=20,
                        verbose_name="Type d'accès",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'accès"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès document",
                "verbose_name_plural": "Accès documents",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(
                        default=academic.models.get_current_date,
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de retrait"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Inscription active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_name",
                    models.CharField(
                        max_length=100, verbose_name="Nom de l'évaluation"
                    ),
                ),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("HOMEWORK", "Devoir"),
                            ("TEST", "Interrogation"),
                            ("EXAM", "Examen"),
                            ("PROJECT", "Projet"),
                            ("PARTICIPATION", "Participation"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type d'évaluation",
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Note obtenue",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Note maximale",
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        max_digits=3,
                        verbose_name="Coefficient",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date d'évaluation")),
                ("comments", models.TextField(blank=True, verbose_name="Commentaires")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du niveau"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Ordre")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom de la période"),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="Période courante"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Période",
                "verbose_name_plural": "Périodes",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de la session")),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de début réelle"
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin réelle"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programmée"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminée"),
                            ("CANCELLED", "Annulée"),
                            ("POSTPONED", "Reportée"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "lesson_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre de la leçon"
                    ),
                ),
                (
                    "lesson_objectives",
                    models.TextField(blank=True, verbose_name="Objectifs de la leçon"),
                ),
                (
                    "lesson_content",
                    models.TextField(blank=True, verbose_name="Contenu de la leçon"),
                ),
                (
                    "lesson_summary",
                    models.TextField(
                        blank=True, verbose_name="Résumé de ce qui a été enseigné"
                    ),
                ),
                (
                    "teacher_notes",
                    models.TextField(blank=True, verbose_name="Notes de l'enseignant"),
                ),
                (
                    "homework_given",
                    models.TextField(blank=True, verbose_name="Devoirs donnés"),
                ),
                (
                    "next_lesson_preparation",
                    models.TextField(
                        blank=True, verbose_name="Préparation pour la prochaine leçon"
                    ),
                ),
                (
                    "attendance_taken",
                    models.BooleanField(default=False, verbose_name="Appel effectué"),
                ),
                (
                    "attendance_taken_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de l'appel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Session de cours",
                "verbose_name_plural": "Sessions de cours",
                "ordering": ["-date", "-timetable__start_time"],
            },
        ),
        migrations.CreateModel(
            name="SessionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du devoir"),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("HOMEWORK", "Devoir maison"),
                            ("EXERCISE", "Exercice"),
                            ("PROJECT", "Projet"),
                            ("RESEARCH", "Recherche"),
                            ("READING", "Lecture"),
                            ("PREPARATION", "Préparation"),
                            ("OTHER", "Autre"),
                        ],
                        default="HOMEWORK",
                        max_length=20,
                        verbose_name="Type de devoir",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Élevée"),
                            ("URGENT", "Urgente"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Date limite de rendu")),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        help_text="En minutes", verbose_name="Durée estimée"
                    ),
                ),
                (
                    "will_be_graded",
                    models.BooleanField(default=True, verbose_name="Sera noté"),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Note maximale",
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        max_digits=3,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="Instructions spécifiques"
                    ),
                ),
                (
                    "resources_needed",
                    models.TextField(blank=True, verbose_name="Ressources nécessaires"),
                ),
                (
                    "submission_format",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Format de rendu"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Publié aux étudiants"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publié le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Devoir de session",
                "verbose_name_plural": "Devoirs de session",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("ABSENT", "Absent"),
                            ("LATE", "En retard"),
                            ("EXCUSED", "Absent excusé"),
                        ],
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure d'arrivée"
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Enregistré le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Présence de session",
                "verbose_name_plural": "Présences de session",
                "ordering": ["student__user__last_name", "student__user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="SessionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Partagé le"),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, verbose_name="Objectif du partage"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, verbose_name="Lecture obligatoire"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date limite de consultation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document de session",
                "verbose_name_plural": "Documents de session",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Titre"),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Générale"),
                            ("BEHAVIOR", "Comportement"),
                            ("PARTICIPATION", "Participation"),
                            ("DIFFICULTY", "Difficulté"),
                            ("ACHIEVEMENT", "Réussite"),
                            ("REMINDER", "Rappel"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="Type de note",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, verbose_name="Note privée (enseignant seulement)"
                    ),
                ),
                (
                    "visible_to_students",
                    models.BooleanField(
                        default=False, verbose_name="Visible aux étudiants"
                    ),
                ),
                (
                    "visible_to_parents",
                    models.BooleanField(
                        default=False, verbose_name="Visible aux parents"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Note de session",
                "verbose_name_plural": "Notes de session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom de la matière"),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Code"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        max_digits=3,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Couleur"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Heures par semaine"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Attribution enseignant",
                "verbose_name_plural": "Attributions enseignants",
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (1, "Lundi"),
                            (2, "Mardi"),
                            (3, "Mercredi"),
                            (4, "Jeudi"),
                            (5, "Vendredi"),
                            (6, "Samedi"),
                            (7, "Dimanche"),
                        ],
                        verbose_name="Jour de la semaine",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "room",
                    models.CharField(blank=True, max_length=50, verbose_name="Salle"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emploi du temps",
                "verbose_name_plural": "Emplois du temps",
                "ordering": ["weekday", "start_time"],
            },
        ),
    ]
