# Generated by Django 5.2.5 on 2025-09-06 14:56

import academic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateField(
                default=academic.models.get_current_date,
                verbose_name="Date d'inscription",
            ),
        ),
    ]
