# Generated by Django 5.2.5 on 2025-09-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_fix_timezone_defaults"),
        ("accounts", "0002_fix_timezone_defaults"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("student", "academic_year"),
                name="unique_active_enrollment_per_year",
            ),
        ),
    ]
