# Generated by Django 5.2.5 on 2025-09-21 10:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_document_documentaccess"),
        ("accounts", "0002_fix_timezone_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date"],
                "verbose_name": "Présence (Ancien)",
                "verbose_name_plural": "Présences (Ancien)",
            },
        ),
        migrations.AlterField(
            model_name="grade",
            name="max_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Note maximale",
            ),
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de la session")),
                (
                    "actual_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de début réelle"
                    ),
                ),
                (
                    "actual_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de fin réelle"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Programmée"),
                            ("IN_PROGRESS", "En cours"),
                            ("COMPLETED", "Terminée"),
                            ("CANCELLED", "Annulée"),
                            ("POSTPONED", "Reportée"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "lesson_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre de la leçon"
                    ),
                ),
                (
                    "lesson_objectives",
                    models.TextField(blank=True, verbose_name="Objectifs de la leçon"),
                ),
                (
                    "lesson_content",
                    models.TextField(blank=True, verbose_name="Contenu de la leçon"),
                ),
                (
                    "lesson_summary",
                    models.TextField(
                        blank=True, verbose_name="Résumé de ce qui a été enseigné"
                    ),
                ),
                (
                    "teacher_notes",
                    models.TextField(blank=True, verbose_name="Notes de l'enseignant"),
                ),
                (
                    "homework_given",
                    models.TextField(blank=True, verbose_name="Devoirs donnés"),
                ),
                (
                    "next_lesson_preparation",
                    models.TextField(
                        blank=True, verbose_name="Préparation pour la prochaine leçon"
                    ),
                ),
                (
                    "attendance_taken",
                    models.BooleanField(default=False, verbose_name="Appel effectué"),
                ),
                (
                    "attendance_taken_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de l'appel"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academic.period",
                        verbose_name="Période",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="academic.timetable",
                        verbose_name="Créneau d'emploi du temps",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session de cours",
                "verbose_name_plural": "Sessions de cours",
                "ordering": ["-date", "-timetable__start_time"],
                "unique_together": {("timetable", "date")},
            },
        ),
        migrations.AddField(
            model_name="document",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_documents",
                to="academic.session",
                verbose_name="Session associée",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades",
                to="academic.session",
                verbose_name="Session associée",
            ),
        ),
        migrations.CreateModel(
            name="SessionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du devoir"),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("HOMEWORK", "Devoir maison"),
                            ("EXERCISE", "Exercice"),
                            ("PROJECT", "Projet"),
                            ("RESEARCH", "Recherche"),
                            ("READING", "Lecture"),
                            ("PREPARATION", "Préparation"),
                            ("OTHER", "Autre"),
                        ],
                        default="HOMEWORK",
                        max_length=20,
                        verbose_name="Type de devoir",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyenne"),
                            ("HIGH", "Élevée"),
                            ("URGENT", "Urgente"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Date limite de rendu")),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        help_text="En minutes", verbose_name="Durée estimée"
                    ),
                ),
                (
                    "will_be_graded",
                    models.BooleanField(default=True, verbose_name="Sera noté"),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Note maximale",
                    ),
                ),
                (
                    "coefficient",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        max_digits=3,
                        verbose_name="Coefficient",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="Instructions spécifiques"
                    ),
                ),
                (
                    "resources_needed",
                    models.TextField(blank=True, verbose_name="Ressources nécessaires"),
                ),
                (
                    "submission_format",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Format de rendu"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Publié aux étudiants"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publié le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="academic.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devoir de session",
                "verbose_name_plural": "Devoirs de session",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="SessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Titre"),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Générale"),
                            ("BEHAVIOR", "Comportement"),
                            ("PARTICIPATION", "Participation"),
                            ("DIFFICULTY", "Difficulté"),
                            ("ACHIEVEMENT", "Réussite"),
                            ("REMINDER", "Rappel"),
                        ],
                        default="GENERAL",
                        max_length=20,
                        verbose_name="Type de note",
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(
                        default=False, verbose_name="Note privée (enseignant seulement)"
                    ),
                ),
                (
                    "visible_to_students",
                    models.BooleanField(
                        default=False, verbose_name="Visible aux étudiants"
                    ),
                ),
                (
                    "visible_to_parents",
                    models.BooleanField(
                        default=False, verbose_name="Visible aux parents"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="academic.session",
                        verbose_name="Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Note de session",
                "verbose_name_plural": "Notes de session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyAttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "total_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de sessions"
                    ),
                ),
                (
                    "present_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions présentes"
                    ),
                ),
                (
                    "absent_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions absentes"
                    ),
                ),
                (
                    "late_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions en retard"
                    ),
                ),
                (
                    "excused_sessions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sessions excusées"
                    ),
                ),
                (
                    "daily_status",
                    models.CharField(
                        choices=[
                            ("FULLY_PRESENT", "Entièrement présent"),
                            ("PARTIALLY_PRESENT", "Partiellement présent"),
                            ("MOSTLY_ABSENT", "Majoritairement absent"),
                            ("FULLY_ABSENT", "Entièrement absent"),
                        ],
                        max_length=20,
                        verbose_name="Statut journalier",
                    ),
                ),
                (
                    "attendance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Taux de présence (%)",
                    ),
                ),
                (
                    "first_arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Première arrivée"
                    ),
                ),
                (
                    "total_late_minutes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total minutes de retard"
                    ),
                ),
                (
                    "justification_provided",
                    models.BooleanField(
                        default=False, verbose_name="Justification fournie"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_summaries",
                        to="accounts.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résumé quotidien de présence",
                "verbose_name_plural": "Résumés quotidiens de présence",
                "ordering": ["-date", "student__user__last_name"],
                "unique_together": {("student", "date")},
            },
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Présent"),
                            ("ABSENT", "Absent"),
                            ("LATE", "En retard"),
                            ("EXCUSED", "Absent excusé"),
                        ],
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure d'arrivée"
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="Justification"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Enregistré le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="academic.session",
                        verbose_name="Session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attendances",
                        to="accounts.student",
                        verbose_name="Élève",
                    ),
                ),
            ],
            options={
                "verbose_name": "Présence de session",
                "verbose_name_plural": "Présences de session",
                "ordering": ["student__user__last_name", "student__user__first_name"],
                "unique_together": {("session", "student")},
            },
        ),
        migrations.CreateModel(
            name="SessionDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Partagé le"),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, verbose_name="Objectif du partage"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, verbose_name="Lecture obligatoire"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date limite de consultation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_links",
                        to="academic.document",
                        verbose_name="Document",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="academic.session",
                        verbose_name="Session",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Partagé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document de session",
                "verbose_name_plural": "Documents de session",
                "ordering": ["-shared_at"],
                "unique_together": {("session", "document")},
            },
        ),
    ]
