# Generated by Django 5.2.5 on 2025-08-31 11:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du modèle"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                (
                    "body_text",
                    models.TextField(verbose_name="Corps du message (texte)"),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True, verbose_name="Corps du message (HTML)"
                    ),
                ),
                (
                    "available_variables",
                    models.JSONField(
                        default=dict, verbose_name="Variables disponibles"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modèle d'e-mail",
                "verbose_name_plural": "Modèles d'e-mail",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "Générale"),
                            ("ACADEMIC", "Académique"),
                            ("EVENT", "Événement"),
                            ("URGENT", "Urgent"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="GENERAL",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "Tous"),
                            ("STUDENTS", "Élèves"),
                            ("PARENTS", "Parents"),
                            ("TEACHERS", "Enseignants"),
                            ("STAFF", "Personnel"),
                            ("CLASS", "Classe spécifique"),
                            ("LEVEL", "Niveau spécifique"),
                        ],
                        default="ALL",
                        max_length=15,
                        verbose_name="Public cible",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Publié"),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de publication"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Épinglé"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Normale"), (2, "Élevée"), (3, "Urgente")],
                        default=1,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(
                        default=False, verbose_name="Envoyer par e-mail"
                    ),
                ),
                (
                    "send_sms",
                    models.BooleanField(default=False, verbose_name="Envoyer par SMS"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "target_classes",
                    models.ManyToManyField(
                        blank=True,
                        to="academic.classroom",
                        verbose_name="Classes ciblées",
                    ),
                ),
                (
                    "target_levels",
                    models.ManyToManyField(
                        blank=True, to="academic.level", verbose_name="Niveaux ciblés"
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-is_pinned", "-priority", "-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail destinataire"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("body", models.TextField(verbose_name="Corps du message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SENT", "Envoyé"),
                            ("DELIVERED", "Livré"),
                            ("FAILED", "Échoué"),
                            ("BOUNCED", "Rejeté"),
                        ],
                        default="PENDING",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "delivered_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de livraison"
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur destinataire",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="communication.emailtemplate",
                        verbose_name="Modèle utilisé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'e-mail",
                "verbose_name_plural": "Journaux d'e-mails",
                "ordering": ["-sent_date"],
            },
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "sent_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_group_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Expéditeur",
                    ),
                ),
                (
                    "target_classes",
                    models.ManyToManyField(
                        blank=True,
                        to="academic.classroom",
                        verbose_name="Classes destinataires",
                    ),
                ),
                (
                    "target_levels",
                    models.ManyToManyField(
                        blank=True,
                        to="academic.level",
                        verbose_name="Niveaux destinataires",
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="received_group_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateurs destinataires",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message de groupe",
                "verbose_name_plural": "Messages de groupe",
                "ordering": ["-sent_date"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Sujet")),
                ("content", models.TextField(verbose_name="Contenu")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "deleted_by_sender",
                    models.BooleanField(
                        default=False, verbose_name="Supprimé par l'expéditeur"
                    ),
                ),
                (
                    "deleted_by_recipient",
                    models.BooleanField(
                        default=False, verbose_name="Supprimé par le destinataire"
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date d'envoi"
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="communication.message",
                        verbose_name="Message parent",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Expéditeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-sent_date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Avertissement"),
                            ("ERROR", "Erreur"),
                            ("SUCCESS", "Succès"),
                            ("ANNOUNCEMENT", "Annonce"),
                            ("MESSAGE", "Message"),
                            ("GRADE", "Note"),
                            ("ATTENDANCE", "Présence"),
                            ("PAYMENT", "Paiement"),
                            ("REMINDER", "Rappel"),
                        ],
                        default="INFO",
                        max_length=15,
                        verbose_name="Type",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "read_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                ("link_url", models.URLField(blank=True, verbose_name="Lien")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document"),
                            ("VIDEO", "Vidéo"),
                            ("AUDIO", "Audio"),
                            ("IMAGE", "Image"),
                            ("LINK", "Lien"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=15,
                        verbose_name="Type de ressource",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="resources/",
                        verbose_name="Fichier",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Public"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Taille du fichier"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de téléchargements"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accessible_classes",
                    models.ManyToManyField(
                        blank=True,
                        to="academic.classroom",
                        verbose_name="Classes autorisées",
                    ),
                ),
                (
                    "accessible_levels",
                    models.ManyToManyField(
                        blank=True,
                        to="academic.level",
                        verbose_name="Niveaux autorisés",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="academic.subject",
                        verbose_name="Matière",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Téléchargé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressource",
                "verbose_name_plural": "Ressources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date d'accès"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "Consultation"),
                            ("DOWNLOAD", "Téléchargement"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="communication.resource",
                        verbose_name="Ressource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Accès à la ressource",
                "verbose_name_plural": "Accès aux ressources",
                "ordering": ["-access_date"],
            },
        ),
        migrations.CreateModel(
            name="AnnouncementRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de lecture",
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_status",
                        to="communication.announcement",
                        verbose_name="Annonce",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture d'annonce",
                "verbose_name_plural": "Lectures d'annonces",
                "unique_together": {("announcement", "user")},
            },
        ),
        migrations.CreateModel(
            name="GroupMessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de lecture",
                    ),
                ),
                (
                    "group_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_status",
                        to="communication.groupmessage",
                        verbose_name="Message de groupe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lecture de message de groupe",
                "verbose_name_plural": "Lectures de messages de groupe",
                "unique_together": {("group_message", "user")},
            },
        ),
    ]
