# Generated by Django 5.2.5 on 2025-10-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="target_roles",
            field=models.CharField(
                blank=True,
                help_text="Liste des rôles séparés par des virgules (ex: STUDENT,PARENT,TEACHER)",
                max_length=200,
                null=True,
                verbose_name="Rôles ciblés",
            ),
        ),
    ]
