# Generated by Django 5.2.5 on 2025-09-04 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_initial"),
        ("communication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Épinglé"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Verrouillé"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Approuvé"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de vues"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_topics",
                        to="academic.classroom",
                        verbose_name="Classe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sujet de forum",
                "verbose_name_plural": "Sujets de forum",
                "ordering": ["-is_pinned", "-updated_at"],
                "permissions": [
                    ("can_moderate_forum", "Peut modérer le forum"),
                    ("can_pin_topics", "Peut épingler des sujets"),
                    ("can_lock_topics", "Peut verrouiller des sujets"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Approuvé"),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Modifié"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Modifié le"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "parent_post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="communication.forumpost",
                        verbose_name="Réponse à",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to="communication.forumtopic",
                        verbose_name="Sujet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post de forum",
                "verbose_name_plural": "Posts de forum",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumModeration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("EDIT", "Modification"),
                            ("DELETE", "Suppression"),
                            ("LOCK", "Verrouillage"),
                            ("UNLOCK", "Déverrouillage"),
                            ("PIN", "Épinglage"),
                            ("UNPIN", "Désépinglage"),
                            ("APPROVE", "Approbation"),
                            ("REJECT", "Rejet"),
                        ],
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Raison")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_moderations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modérateur",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderations",
                        to="communication.forumpost",
                        verbose_name="Post",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderations",
                        to="communication.forumtopic",
                        verbose_name="Sujet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modération de forum",
                "verbose_name_plural": "Modérations de forum",
                "ordering": ["-created_at"],
            },
        ),
    ]
