# Generated by Django 5.2.5 on 2025-09-06 14:56

import communication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_forumtopic_forumpost_forummoderation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementread",
            name="read_date",
            field=models.DateTimeField(
                default=communication.models.get_current_datetime,
                verbose_name="Date de lecture",
            ),
        ),
        migrations.AlterField(
            model_name="emaillog",
            name="sent_date",
            field=models.DateTimeField(
                default=communication.models.get_current_datetime,
                verbose_name="Date d'envoi",
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="sent_date",
            field=models.DateTimeField(
                default=communication.models.get_current_datetime,
                verbose_name="Date d'envoi",
            ),
        ),
        migrations.AlterField(
            model_name="groupmessageread",
            name="read_date",
            field=models.DateTimeField(
                default=communication.models.get_current_datetime,
                verbose_name="Date de lecture",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sent_date",
            field=models.DateTimeField(
                default=communication.models.get_current_datetime,
                verbose_name="Date d'envoi",
            ),
        ),
        migrations.AlterField(
            model_name="resourceaccess",
            name="access_date",
            field=models.DateTimeField(
                default=communication.models.get_current_datetime,
                verbose_name="Date d'accès",
            ),
        ),
    ]
